package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EditoraAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEditoraAllPropertiesEquals(Editora expected, Editora actual) {
        assertEditoraAutoGeneratedPropertiesEquals(expected, actual);
        assertEditoraAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEditoraAllUpdatablePropertiesEquals(Editora expected, Editora actual) {
        assertEditoraUpdatableFieldsEquals(expected, actual);
        assertEditoraUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEditoraAutoGeneratedPropertiesEquals(Editora expected, Editora actual) {
        assertThat(expected)
            .as("Verify Editora auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEditoraUpdatableFieldsEquals(Editora expected, Editora actual) {
        assertThat(expected)
            .as("Verify Editora relevant properties")
            .satisfies(e -> assertThat(e.getNome()).as("check nome").isEqualTo(actual.getNome()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEditoraUpdatableRelationshipsEquals(Editora expected, Editora actual) {}
}
