package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class IdiomaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIdiomaAllPropertiesEquals(Idioma expected, Idioma actual) {
        assertIdiomaAutoGeneratedPropertiesEquals(expected, actual);
        assertIdiomaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIdiomaAllUpdatablePropertiesEquals(Idioma expected, Idioma actual) {
        assertIdiomaUpdatableFieldsEquals(expected, actual);
        assertIdiomaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIdiomaAutoGeneratedPropertiesEquals(Idioma expected, Idioma actual) {
        assertThat(expected)
            .as("Verify Idioma auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIdiomaUpdatableFieldsEquals(Idioma expected, Idioma actual) {
        assertThat(expected)
            .as("Verify Idioma relevant properties")
            .satisfies(e -> assertThat(e.getNome()).as("check nome").isEqualTo(actual.getNome()))
            .satisfies(e -> assertThat(e.getDescricao()).as("check descricao").isEqualTo(actual.getDescricao()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIdiomaUpdatableRelationshipsEquals(Idioma expected, Idioma actual) {}
}
